{{- if .Values.cp4waiops.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4waiops
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-cp4waiops` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: '{{ .Values.cp4waiops.namespace }}'
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: config/cp4waiops/3.2
        repoURL: https://github.com/morningspace/cp4waiops-sandbox
        targetRevision: HEAD
        helm:
          {{- if eq .Values.cp4waiops.profile "x-small" }}
          valueFiles:
            - 'values.x-small.yaml'
          {{- end }}
          parameters:
            - name: cp4waiops32.spec.dockerPassword
              value: '{{ .Values.cp4waiops.dockerPassword }}'
            - name: cp4waiops32.spec.aiManager.instanceName
              value: '{{ .Values.cp4waiops.instanceName }}'
            - name: cp4waiops32.spec.storageClass
              value: '{{ .Values.cp4waiops.storageClass }}'
            - name: cp4waiops32.spec.storageClassLargeBlock
              value: '{{ .Values.cp4waiops.storageClassLargeBlock }}'
            - name: cp4waiops32.spec.aiManager.namespace
              value: '{{ .Values.cp4waiops.namespace }}'
            {{- if eq .Values.cp4waiops.profile "x-small" }}
            - name: cp4waiops32.spec.size
              value: 'small'
            {{- else }}
            - name: cp4waiops32.spec.size
              value: '{{ .Values.cp4waiops.profile }}'
            {{- end }}
      ignoreDifferences:
        - group: orchestrator.aiops.ibm.com
          jsonPointers:
            - /spec/pakModules
          kind: Installation
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
{{- end }}